[project]
name = "genai-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain>=1.4.0",
    "langchain-anthropic>=1.7.1",
    "langchain-google-genai>=4.4.0",
    "langchain-openai>=1.6.2",
    "python-dotenv>=1.2.3",
]
